FROM ruby:2.6.5

RUN apt-get update -qq && apt-get install -y \
  unzip \
  build-essential \
  tzdata \
  libgconf-2-4 \
  libpq-dev \
  ghostscript \
  libgs-dev \
  imagemagick \
  apt-transport-https

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
    && apt-get install -y nodejs

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt update

RUN apt install yarn

WORKDIR /app
ADD Gemfile* /app/
RUN bundle install

ADD . .

RUN rails credentials:edit
#RUN rails g rails_admin:install
#RUN bundle exec rake SECRET_KEY_BASE=838d32f2bece128979af6d0a3c406a4f39c5ff3a85f900bf17886081148fc22e262b4929ce7475324088bde8b101bad8f0d5579c8feed4e3a9d232402c625340 assets:precompile
RUN rails webpacker:install
CMD bundle exec rails server -b 0.0.0.0