sudo: required
services:
    - docker

before_install:
    - docker build -t mayacine/ngx-admin -f ./ngx-admin/Dockerfile-dev ./ngx-admin
    - docker build -t mayacine/sms-management -f ./sms-management/Dockerfile-dev ./sms-management

script:
  - docker run mayacine/sms-management rails test